#
# Makefile for Chapter 12
#
# Type  make    to compile all the programs
# in the chapter 
#
all: tcps tcpc

clean:
	rm -f *.o tcps tcpc
clien:
	cc -o tcpc socklib.c tcpc.c 
server:
	cc -o tcps socklib.c tcps.c



